trigger:
- main

pr:
- main

jobs:
- job: Jobs
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo Hi
      echo final
    displayName: 'test'

- job: test
  timeoutInMinutes: 2
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      echo Hi
      echo final
      sleep 75m
    displayName: 'test'
